# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

!if "$(VERBOSE)" != "1"
VV=@
!endif

AS=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\HostX64\x64\ml64.exe
GC=go
CC=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\HostX64\x64\cl.exe
CU=C:\Program Files\LLVM\bin\clang
MRC=C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64\rc.exe
CXX=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\HostX64\x64\cl.exe
RC=rustc

LD=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\HostX64\x64\link.exe
RCLD=rustc
GCLD=go
AR=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\HostX64\x64\link.exe
RCAR=rustc
GCAR=go
SH=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\HostX64\x64\link.exe
RCSH=rustc

main_LD=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\HostX64\x64\link.exe
main_CXX=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\HostX64\x64\cl.exe
main_CXX=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\HostX64\x64\cl.exe

main_CXXFLAGS=-nologo /EHsc -external:W0 -external:IC:\Users\rose\AppData\Local\.xmake\packages\r\raylib\5.5\408c30abf64a45a68c13bf6f56269c94\include
main_CXXFLAGS=-nologo /EHsc -external:W0 -external:IC:\Users\rose\AppData\Local\.xmake\packages\r\raylib\5.5\408c30abf64a45a68c13bf6f56269c94\include
main_LDFLAGS=-nologo -dynamicbase -nxcompat -machine:x64 -libpath:C:\Users\rose\AppData\Local\.xmake\packages\r\raylib\5.5\408c30abf64a45a68c13bf6f56269c94\lib raylib.lib opengl32.lib gdi32.lib user32.lib winmm.lib shell32.lib

default:  main

all:  main

.PHONY: default all  main

main: build\windows\x64\release\main.exe
build\windows\x64\release\main.exe: build\.objs\main\windows\x64\release\src\main.cpp.obj
	@echo linking.release main.exe
	-@mkdir build\windows\x64\release > NUL 2>&1
	$(VV)"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.42.34433\\bin\\HostX64\\x64\\link.exe" $(main_LDFLAGS) -out:build\windows\x64\release\main.exe build\.objs\main\windows\x64\release\src\main.cpp.obj

build\.objs\main\windows\x64\release\src\main.cpp.obj: src\main.cpp
	@echo compiling.release src\main.cpp
	-@mkdir build\.objs\main\windows\x64\release\src > NUL 2>&1
	$(VV)"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.42.34433\\bin\\HostX64\\x64\\cl.exe" -c $(main_CXXFLAGS) -Fobuild\.objs\main\windows\x64\release\src\main.cpp.obj src\main.cpp

clean:  clean_main

clean_main: 
	@del /F /Q build\windows\x64\release\main.exe > NUL 2>&1 || rmdir /S /Q build\windows\x64\release\main.exe > NUL 2>&1
	@del /F /Q build\windows\x64\release\main.pdb > NUL 2>&1 || rmdir /S /Q build\windows\x64\release\main.pdb > NUL 2>&1
	@del /F /Q build\.objs\main\windows\x64\release\src\main.cpp.obj > NUL 2>&1 || rmdir /S /Q build\.objs\main\windows\x64\release\src\main.cpp.obj > NUL 2>&1

